### PR TITLE
Removed commonjs syntax

### PR DESCRIPTION
**Pull request by connorsmallman**

### CODE REVIEW

**Comment by alexnewmannn** [comment]
Seems like theres a few more places that have bee missed, excluding libraries - https://github.com/BedeGaming/orchestra/search?utf8=%E2%9C%93&q=module.exports

**Comment by connorsmallman** [comment]
Some of them are used in the mocha tests that unfortunately doesn't support ES6 yet.

**Comment by ahumphreys87** [comment]
@connorsmallman could you rebase this from master to trigger a travis build please?

**Comment by ahumphreys87** [comment]
manually merged

**Pull request closed without merging**
